import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

const TABS = [
  { key: 'req',    label: 'Requirements (1 & 2)', icon: '📋' },
  { key: 'class',  label: 'Class Diagram (3)',     icon: '🏗️' },
  { key: 'schema', label: 'Schema Design (4)',      icon: '🗄️' },
];

const mdComponents = {
  h2: ({children}) => <h2 className="text-lg font-bold text-white mt-5 mb-2 border-b border-navy-800 pb-1">{children}</h2>,
  h3: ({children}) => <h3 className="text-base font-semibold text-electric-400 mt-4 mb-1.5">{children}</h3>,
  h4: ({children}) => <h4 className="text-sm font-semibold text-navy-200 mt-3 mb-1">{children}</h4>,
  p:  ({children}) => <p  className="text-sm text-navy-300 leading-relaxed mb-3">{children}</p>,
  ul: ({children}) => <ul className="list-disc pl-5 mb-3 flex flex-col gap-1">{children}</ul>,
  li: ({children}) => <li className="text-sm text-navy-300 leading-relaxed">{children}</li>,
  strong: ({children}) => <strong className="text-white font-semibold">{children}</strong>,
  code: ({inline, children}) => inline
    ? <code className="bg-navy-800 text-electric-400 px-1.5 py-0.5 rounded text-xs font-mono">{children}</code>
    : <pre className="bg-navy-900 border border-navy-800 rounded-xl p-4 overflow-x-auto text-xs text-electric-300 font-mono my-3">{children}</pre>,
  blockquote: ({children}) => <blockquote className="border-l-4 border-electric-600 pl-4 italic text-navy-400 my-3">{children}</blockquote>,
};

export default function FeedbackModal({ isOpen, feedback, onClose, onRestart }) {
  const [tab, setTab] = useState('req');
  if (!isOpen) return null;

  const content = feedback[tab];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-8"
         style={{background:'rgba(6,13,26,0.9)', backdropFilter:'blur(12px)'}}>
      <div className="w-full max-w-3xl h-[88vh] glass rounded-2xl flex flex-col overflow-hidden fade-up border border-navy-700">

        {/* Header */}
        <div className="p-5 border-b border-navy-800 flex items-center justify-between shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-electric-600 to-indigo-600 flex items-center justify-center text-lg">🏆</div>
            <div>
              <h2 className="text-white font-bold text-base">JARVIS Scorecard</h2>
              <p className="text-navy-400 text-xs">Detailed LLD performance review</p>
            </div>
          </div>
          <button onClick={onClose}
            className="p-2 rounded-xl hover:bg-navy-800 text-navy-500 hover:text-white transition-colors text-lg leading-none">✕</button>
        </div>

        {/* Tabs */}
        <div className="flex border-b border-navy-800 shrink-0 overflow-x-auto">
          {TABS.map(t => (
            <button key={t.key} id={`tab-${t.key}`} onClick={() => setTab(t.key)}
              className={`px-5 py-3 text-sm font-semibold border-b-2 whitespace-nowrap transition-all ${
                tab === t.key
                  ? 'border-electric-500 text-electric-400 bg-electric-500/5'
                  : 'border-transparent text-navy-400 hover:text-navy-200'
              }`}>
              {t.icon} {t.label}
            </button>
          ))}
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          {content ? (
            <ReactMarkdown remarkPlugins={[remarkGfm]} components={mdComponents}>{content}</ReactMarkdown>
          ) : (
            <div className="flex flex-col items-center justify-center h-full text-center gap-4">
              <div className="text-4xl opacity-40">📊</div>
              <p className="text-navy-500 text-sm">Complete this phase in the interview to unlock feedback.</p>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-navy-800 flex justify-between items-center shrink-0">
          <p className="text-[11px] text-navy-600">Feedback generated by Claude Sonnet · Flipkart SDE-2 standards</p>
          <div className="flex gap-2">
            <button onClick={onRestart}
              className="px-4 py-2 rounded-xl border border-navy-700 hover:bg-navy-800 text-sm text-navy-300 hover:text-white transition-all">
              New Interview
            </button>
            <button onClick={onClose}
              className="px-4 py-2 rounded-xl bg-electric-600 hover:bg-electric-500 text-sm text-white font-semibold transition-all">
              Back to Interview
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
